<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Culinario.Application\Culinario.Application.csproj" />
    <ProjectReference Include="..\Culinario.Infrastructure\Culinario.Infrastructure.csproj" />
  </ItemGroup>

</Project>
